### ISSUE TITLE
Notfound

### ISSUE THREAD

**Issue by nimafire** [itsamirhn/Bonbast-API#1]
herokuapp.com
not found. any update regarding this project to let us get $ rate like into a php file ?

**Comment by itsamirhn** [comment]
I'm not sure about what are you saying, but you can get **yesterday** USD price by fetching https://bonbast-api.deta.dev/archive/. This is php code as you want:
```php
$json = file_get_contents('https://bonbast-api.deta.dev/archive/');
$obj = json_decode($json);
echo $obj->usd->sell;
echo PHP_EOL;
echo $obj->usd->buy;
```

I will implement the **latest** price in the next few days.

**Comment by itsamirhn** [comment]
New API has been implemented. Now you can fetch https://bonbast-api.deta.dev/latest for latest currency price (30 minutes cache)
